backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "services"
    label: "الخدمات"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان الخدمة", name: "title", widget: "string" }
      - { label: "وصف مختصر", name: "summary", widget: "string" }
      - { label: "الوصف", name: "body", widget: "markdown" }
      - { label: "الصورة", name: "image", widget: "image" }

  - name: "projects"
    label: "معرض الأعمال"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المشروع", name: "title", widget: "string" }
      - { label: "الوصف", name: "body", widget: "markdown" }
      - { label: "الصورة", name: "image", widget: "image" }

  - name: "contact"
    label: "تواصل مع رائد"
    files:
      - file: "content/contact/info.md"
        name: "contactinfo"
        label: "معلومات التواصل"
        fields:
          - { label: "رقم الواتساب", name: "whatsapp", widget: "string" }
          - { label: "الايميل", name: "email", widget: "string" }
          - { label: "رسالة الترحيب", name: "welcome", widget: "text" }
