backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "services"
    label: "الخدمات"
    folder: "content/services"
    create: true
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف المختصر", name: "summary", widget: "string" }
      - { label: "الوصف", name: "body", widget: "markdown" }
      - { label: "الصورة", name: "image", widget: "image" }

  - name: "projects"
    label: "معرض الأعمال"
    folder: "content/projects"
    create: true
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
      - { label: "الصورة", name: "image", widget: "image" }

  - name: "contact"
    label: "تواصل معي"
    folder: "content/contact"
    create: true
    fields:
      - { label: "رقم الواتساب", name: "whatsapp", widget: "string" }
      - { label: "الإيميل", name: "email", widget: "string" }
      - { label: "الرسالة الترحيبية", name: "message", widget: "markdown" }
